apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/cloudk8sa3/kubernetes-images/container1:latest
        ports:
        - containerPort: 6000
        volumeMounts:
        - mountPath: /mnt/data
          name: saikumar-storage
      volumes:
      - name: saikumar-storage
        persistentVolumeClaim:
          claimName: saikumar-pvc
