apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/cloudk8sa3/kubernetes-images/container2:latest
        ports:
        - containerPort: 6001
        volumeMounts:
        - mountPath: /saikumar_PV_dir/
          name: saikumar-storage
      volumes:
      - name: saikumar-storage
        persistentVolumeClaim:
          claimName: saikumar-pvc