apiVersion: v1
kind: PersistentVolume
metadata:
  name: saikumar-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /saikumar_PV_dir/
  storageClassName: manual
