apiVersion: v1
kind: PersistentVolume
metadata:
  name: saikumar-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standardgit
  gcePersistentDisk:
    pdName: gke-persistentvol-disk  
    fsType: ext4