apiVersion: v1
kind: PersistentVolume
metadata:
  name: saikumar-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: saikumar-storage
  gcePersistentDisk:
    pdName: gke-persistentvol-disk
    fsType: ext4
