apiVersion: v1
kind: PersistentVolume
metadata:
  name: saikumar-pv
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  
  gcePersistentDisk:
    pdName: gke-persistentvol-disk
    fsType: ext4
