apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saikumar-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: custom-storageclass