apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  selector:
    app: container1
  ports:
    - port: 80
      targetPort: 6000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  selector:
    app: container2
  ports:
  - port: 6001
    targetPort: 6001
    protocol: TCP